# Generated by Django 3.1.7 on 2021-04-20 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_emailpush'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='emailpush',
            new_name='email_push',
        ),
    ]
