# Generated by Django 3.1.7 on 2021-04-21 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210420_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_push',
        ),
    ]
